# Combine files

In [1]:
import os
import re
import glob
import pandas as pd
from collections import defaultdict

## check if any duplicate from postbody

In [79]:
from collections import Counter

data = """210A10300 岐阜営業チーム_Date.txt %8A%F2%95%8C%89%63%8B%C6%83%60%81%5B%83%80
210A30200 岐阜工務チーム_Date.txt %8A%F2%95%8C%8D%48%96%B1%83%60%81%5B%83%80
220C10300 中日本営業部_Date.txt %92%86%93%FA%96%7B%89%63%8B%C6%95%94
230A10400 東三河営業部_Date.txt %93%8C%8E%4F%89%CD%89%63%8B%C6%95%94
230H10700 営業推進室_Date.txt %89%63%8B%C6%90%84%90%69%8E%BA
230H62000 人財品質課_Date.txt %90%6C%8D%E0%95%69%8E%BF%89%DB
230H10100 推進チーム_Date.txt %90%84%90%69%83%60%81%5B%83%80
003000000 イノチオアグリ㈱_Date.txt %83C%83m%83%60%83I%83A%83O%83%8A%87%8A
003010100 営業本部_Date.txt %89c%8B%C6%96%7B%95%94
003030100 技術本部_Date.txt %8BZ%8Fp%96%7B%95%94
003060100 経営本部_Date.txt %8Co%89c%96%7B%95%94
003090100 イノチオアグリ本社_Date.txt %83C%83m%83%60%83I%83A%83O%83%8A%96%7B%8E%D0
003090200 本社収支_Date.txt %96%7B%8E%D0%8E%FB%8Ex
003090300 一般ユーザー権限_Date.txt %88%EA%94%CA%83%86%81%5B%83U%81%5B%8C%A0%8C%C0
003090400 経営管理者権限_Date.txt %8Co%89c%8A%C7%97%9D%8E%D2%8C%A0%8C%C0
003090500 システム管理者権限_Date.txt %83V%83X%83e%83%80%8A%C7%97%9D%8E%D2%8C%A0%8C%C0
003091300 田原事業所共通_Date.txt %93c%8C%B4%8E%96%8B%C6%8F%8A%8B%A4%92%CA
003091500 高師事業所共通_Date.txt %8D%82%8Et%8E%96%8B%C6%8F%8A%8B%A4%92%CA
003092100 田原工場共通_Date.txt %93c%8C%B4%8DH%8F%EA%8B%A4%92%CA
003095310 原価用開発(営業)_Date.txt %8C%B4%89%BF%97p%8AJ%94%AD%28%89c%8B%C6%29
003095320 原価用開発(工務)_Date.txt %8C%B4%89%BF%97p%8AJ%94%AD%28%8DH%96%B1%29
003095410 原価用品質管理課(営業)_Date.txt %8C%B4%89%BF%97p%95i%8E%BF%8A%C7%97%9D%89%DB%28%89c%8B%C6%29
003095420 原価用品質管理課(工務)_Date.txt %8C%B4%89%BF%97p%95i%8E%BF%8A%C7%97%9D%89%DB%28%8DH%96%B1%29
040A10100 宮城営業チーム_Date.txt %8B%7B%8F%E9%89c%8B%C6%83%60%81%5B%83%80
040A10200 福島営業チーム_Date.txt %95%9F%93%87%89c%8B%C6%83%60%81%5B%83%80
040A10300 宮城営業課_Date.txt %8B%7B%8F%E9%89c%8B%C6%89%DB
040A10400 福島営業課_Date.txt %95%9F%93%87%89c%8B%C6%89%DB
040A30101 宮城工務チーム_Date.txt %8B%7B%8F%E9%8DH%96%B1%83%60%81%5B%83%80
040A30201 福島工務チーム_Date.txt %95%9F%93%87%8DH%96%B1%83%60%81%5B%83%80
100A10100 東日本営業部_Date.txt %93%8C%93%FA%96%7B%89c%8B%C6%95%94
100A10200 関東営業チーム_Date.txt %8A%D6%93%8C%89c%8B%C6%83%60%81%5B%83%80
100A10300 関東営業課_Date.txt %8A%D6%93%8C%89c%8B%C6%89%DB
100A30101 関東工務チーム_Date.txt %8A%D6%93%8C%8DH%96%B1%83%60%81%5B%83%80
220C10100 浜松営業チーム_Date.txt %95l%8F%BC%89c%8B%C6%83%60%81%5B%83%80
220C10200 浜松営業課_Date.txt %95l%8F%BC%89c%8B%C6%89%DB
220C30101 浜松工務チーム_Date.txt %95l%8F%BC%8DH%96%B1%83%60%81%5B%83%80
230A10100 東海営業部_Date.txt %93%8C%8AC%89c%8B%C6%95%94
230A10200 渥美営業チーム_Date.txt %88%AD%94%FC%89c%8B%C6%83%60%81%5B%83%80
230A10300 渥美営業課_Date.txt %88%AD%94%FC%89c%8B%C6%89%DB
230A30101 渥美工務チーム_Date.txt %88%AD%94%FC%8DH%96%B1%83%60%81%5B%83%80
230B10100 営農支援部_Date.txt %89c%94_%8Ex%89%87%95%94
230B10200 田原営業チーム_Date.txt %93c%8C%B4%89c%8B%C6%83%60%81%5B%83%80
230B10300 田原営業課_Date.txt %93c%8C%B4%89c%8B%C6%89%DB
230B30100 設計開発部_Date.txt %90%DD%8Cv%8AJ%94%AD%95%94
230B30200 設計課_Date.txt %90%DD%8Cv%89%DB
230B30300 システム設計課_Date.txt %83V%83X%83e%83%80%90%DD%8Cv%89%DB
230B30601 田原工務チーム_Date.txt %93c%8C%B4%8DH%96%B1%83%60%81%5B%83%80
230B50100 開発課_Date.txt %8AJ%94%AD%89%DB
230B60100 物流チーム_Date.txt %95%A8%97%AC%83%60%81%5B%83%80
230C30200 製造部_Date.txt %90%BB%91%A2%95%94
230C30310 施設加工課_Date.txt %8E%7B%90%DD%89%C1%8DH%89%DB
230C30330 資材物流課_Date.txt %8E%91%8D%DE%95%A8%97%AC%89%DB
230C30400 工務統括部_Date.txt %8DH%96%B1%93%9D%8A%87%95%94
230C30500 工務管理課_Date.txt %8DH%96%B1%8A%C7%97%9D%89%DB
230C30600 メンテナンス課_Date.txt %83%81%83%93%83e%83i%83%93%83X%89%DB
230H10200 マーケティング課_Date.txt %83%7D%81%5B%83P%83e%83B%83%93%83O%89%DB
230H10400 西日本営業部_Date.txt %90%BC%93%FA%96%7B%89c%8B%C6%95%94
230H10500 本社営業チーム_Date.txt %96%7B%8E%D0%89c%8B%C6%83%60%81%5B%83%80
230H10600 本社営業課_Date.txt %96%7B%8E%D0%89c%8B%C6%89%DB
230H30200 本社工務チーム_Date.txt %96%7B%8E%D0%8DH%96%B1%83%60%81%5B%83%80
230H61100 管理部_Date.txt %8A%C7%97%9D%95%94
230H61210 管理課_Date.txt %8A%C7%97%9D%89%DB
230H61600 企画部_Date.txt %8A%E9%89%E6%95%94
230J30100 フィルム加工課_Date.txt %83t%83B%83%8B%83%80%89%C1%8DH%89%DB
230J30110 フィルム加工課 生産部門_Date.txt %83t%83B%83%8B%83%80%89%C1%8DH%89%DB%20%90%B6%8EY%95%94%96%E5
230J30120 フィルム加工課 出荷部門_Date.txt %83t%83B%83%8B%83%80%89%C1%8DH%89%DB%20%8Fo%89%D7%95%94%96%E5
230K10100 豊橋営業チーム_Date.txt %96L%8B%B4%89c%8B%C6%83%60%81%5B%83%80
230K10200 豊橋営業課_Date.txt %96L%8B%B4%89c%8B%C6%89%DB
230K10300 農薬推進課_Date.txt %94_%96%F2%90%84%90i%89%DB
230K30101 豊橋工務チーム_Date.txt %96L%8B%B4%8DH%96%B1%83%60%81%5B%83%80
230P10100 東海支援課_Date.txt %93%8C%8AC%8Ex%89%87%89%DB
230P10300 豊川営業チーム_Date.txt %96L%90%EC%89c%8B%C6%83%60%81%5B%83%80
230P10400 豊川営業課_Date.txt %96L%90%EC%89c%8B%C6%89%DB
230P30101 豊川工務チーム_Date.txt %96L%90%EC%8DH%96%B1%83%60%81%5B%83%80
230Q10200 西三河営業チーム_Date.txt %90%BC%8EO%89%CD%89c%8B%C6%83%60%81%5B%83%80
230Q10300 西三河営業課_Date.txt %90%BC%8EO%89%CD%89c%8B%C6%89%DB
230Q30101 西三河工務チーム_Date.txt %90%BC%8EO%89%CD%8DH%96%B1%83%60%81%5B%83%80
230S10200 尾張営業チーム_Date.txt %94%F6%92%A3%89c%8B%C6%83%60%81%5B%83%80
230S10300 尾張営業課_Date.txt %94%F6%92%A3%89c%8B%C6%89%DB
230S30101 尾張工務チーム_Date.txt %94%F6%92%A3%8DH%96%B1%83%60%81%5B%83%80
400A10100 広域支援課_Date.txt %8DL%88%E6%8Ex%89%87%89%DB
400A10200 福岡営業チーム_Date.txt %95%9F%89%AA%89c%8B%C6%83%60%81%5B%83%80
400A10300 福岡営業課_Date.txt %95%9F%89%AA%89c%8B%C6%89%DB
400A30100 福岡工務チーム_Date.txt %95%9F%89%AA%8DH%96%B1%83%60%81%5B%83%80
"""

# normalize and split lines
lines = [line.strip() for line in data.strip().split("\n") if line.strip()]

# count duplicates
counter = Counter(lines)

# print duplicates
duplicates = [line for line, count in counter.items() if count > 1]

if duplicates:
    print("Duplicate rows found:")
    for d in duplicates:
        print(d)
else:
    print("No duplicate rows.")

No duplicate rows.

## Delete rows contain a date

In [ ]:
target_file = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Added Columns\PKTR022_アグリ.csv"

df_tmp = pd.read_csv(
    target_file,
    delimiter="\t",
    encoding="utf-8-sig",
    dtype={"対象年月度": str},
    keep_default_na=False
)

before_rows = len(df_tmp)
df_tmp["対象年月度"] = df_tmp["対象年月度"].astype(str).str.strip()
df_tmp = df_tmp[df_tmp["対象年月度"] != "202604"].copy()
removed_rows = before_rows - len(df_tmp)

df_tmp.to_csv(target_file, index=False, sep="\t", encoding="utf-8-sig")

print(f"Removed rows (対象年月度=202604): {removed_rows}")
print(f"Remaining rows: {len(df_tmp)}")
print(f"Updated file: {target_file}")

Removed rows (対象年月度=202604): 4735
Remaining rows: 222428
Updated file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Added Columns\PKTR022_アグリ.csv

In [16]:
target_file = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Added Columns\PKTR022_アグリ.csv"

df_tmp = pd.read_csv(
    target_file,
    delimiter="\t",
    encoding="utf-8-sig",
    dtype={"対象年月度": str},
    keep_default_na=False
)

before_rows = len(df_tmp)

df_tmp["対象年月度"] = df_tmp["対象年月度"].astype(str).str.strip()

# ✅ Remove range 202504–202603
df_tmp = df_tmp[
    ~((df_tmp["対象年月度"] >= "202504") & (df_tmp["対象年月度"] <= "202603"))
].copy()

removed_rows = before_rows - len(df_tmp)

df_tmp.to_csv(target_file, index=False, sep="\t", encoding="utf-8-sig")

print(f"Removed rows (202504–202603): {removed_rows}")
print(f"Remaining rows: {len(df_tmp)}")
print(f"Updated file: {target_file}")

Removed rows (202504–202603): 61484
Remaining rows: 160944
Updated file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Added Columns\PKTR022_アグリ.csv

## Find lack company code based on date compared to 2025 ----------------------------------------------------------------------

## Remove unecessary code

In [73]:
def read_file(path):
    return pd.read_csv(
        path,
        encoding="cp932",
        sep=",",
        on_bad_lines="skip",
        dtype={"組織コード": str},
        keep_default_na=False
    )

ref_2025 = {
 '003000000': 'イノチオアグリ㈱',
 '003090100': 'イノチオアグリ本社',
 '230B30300': 'システム設計課',
 '230J30120': 'フィルム加工課 出荷部門',
 '230J30110': 'フィルム加工課 生産部門',
 '230J30100': 'フィルム加工課',
 '230H10200': 'マーケティング課',
 '230C30600': 'メンテナンス課',
 '230H62000': '人財育成課',
 '230H61600': '企画部',
 '230C60100': '品質管理課',
 '230H10100': '営業推進室',
 '230B10100': '営農支援部',
 '040A10100': '宮城営業チーム',
 '040A10300': '宮城営業課',
 '040A30101': '宮城工務チーム',
 '230S10200': '尾張営業チーム',
 '230S10300': '尾張営業課',
 '230S30101': '尾張工務チーム',
 '230C30500': '工務管理課',
 '230C30400': '工務統括部',
 '400A10100': '広域支援課',
 '003030100': '技術本部',
 '230C30310': '施設加工課',
 '003090200': '本社収支',
 '230H10500': '本社営業チーム',
 '230H10600': '本社営業課',
 '230H30200': '本社工務チーム',
 '230P10100': '東海支援課',
 '220C10100': '浜松営業チーム',
 '220C10200': '浜松営業課',
 '220C30101': '浜松工務チーム',
 '230A10200': '渥美営業チーム',
 '230A10300': '渥美営業課',
 '230A30101': '渥美工務チーム',
 '230B60100': '物流チーム',
 '230B10200': '田原営業チーム',
 '230B10300': '田原営業課',
 '230B30601': '田原工務チーム',
 '400A10200': '福岡営業チーム',
 '400A10300': '福岡営業課',
 '400A30100': '福岡工務チーム',
 '040A10200': '福島営業チーム',
 '040A10400': '福島営業課',
 '040A30201': '福島工務チーム',
 '230H61210': '管理課',
 '230H61100': '管理部',
 '003060100': '経営本部',
 '230C30200': '製造部',
 '230Q10200': '西三河営業チーム',
 '230Q10300': '西三河営業課',
 '230Q30101': '西三河工務チーム',
 '230B30200': '設計課',
 '230B30100': '設計開発部',
 '230H61500': '調達チーム',
 '230P10300': '豊川営業チーム',
 '230P10400': '豊川営業課',
 '230P30101': '豊川工務チーム',
 '230K10100': '豊橋営業チーム',
 '230K10200': '豊橋営業課',
 '230K30101': '豊橋工務チーム',
 '230C30330': '資材物流課',
 '230H61800': '購買課',
 '230K10300': '農薬推進課',
 '230B50100': '開発課',
 '100A10200': '関東営業チーム',
 '100A10300': '関東営業課',
 '100A30101': '関東工務チーム'
}
# Read 2025.txt
actual_2025_df = read_file(r"C:\Users\2372\Downloads\2025.txt")
actual_2025 = dict(zip(actual_2025_df["組織コード"], actual_2025_df["組織名"]))

ref_codes = set(ref_2025.keys())
actual_codes = set(actual_2025.keys())

only_in_ref = ref_codes - actual_codes
only_in_actual = actual_codes - ref_codes
common_codes = ref_codes & actual_codes

name_diff = {
    code: {"ref": ref_2025[code], "actual": actual_2025[code]}
    for code in common_codes
    if ref_2025[code] != actual_2025[code]
}

print(f"Only in reference (missing in file): {sorted(only_in_ref)}")
print(f"\nOnly in file (extra codes): {sorted(only_in_actual)}")
print(f"\nName mismatches ({len(name_diff)}):")
for code, diff in sorted(name_diff.items()):
    print(f"  {code}: ref='{diff['ref']}' | actual='{diff['actual']}'")

Only in reference (missing in file): []

Only in file (extra codes): ['003010100', '003090300', '003090400', '003090500', '003091300', '003091500', '003092100', '003095310', '003095320', '003095410', '003095420', '100A10100', '210A10200', '230A10100', '230H10400']

Name mismatches (0):

In [50]:
len(only_in_actual)

4

## Count rows that contain codes in only_in_actual for each file in file_paths

In [74]:
target_codes = {str(c).strip() for c in only_in_actual}

file_paths = [
    r"C:\Users\2372\Downloads\2022.txt",
    r"C:\Users\2372\Downloads\2023.txt",
    r"C:\Users\2372\Downloads\2024.txt",
    r"C:\Users\2372\Downloads\2025.txt",
    r"C:\Users\2372\Downloads\2026.txt",
]

count_rows = []
detail_rows = []

for path in file_paths:
    df_tmp = pd.read_csv(
        path,
        encoding="cp932",
        sep=",",
        on_bad_lines="skip",
        dtype={"組織コード": str},
        keep_default_na=False
    )
    df_tmp.columns = [c.strip() for c in df_tmp.columns]

    if "組織コード" not in df_tmp.columns:
        count_rows.append({"file": os.path.basename(path), "matched_rows": None, "note": "組織コード column not found"})
        continue

    df_tmp["組織コード"] = df_tmp["組織コード"].astype(str).str.strip()
    matched = df_tmp[df_tmp["組織コード"].isin(target_codes)]

    count_rows.append({
        "file": os.path.basename(path),
        "matched_rows": len(matched),
        "matched_unique_codes": matched["組織コード"].nunique()
    })

    if not matched.empty:
        per_code = matched["組織コード"].value_counts().rename_axis("組織コード").reset_index(name="row_count")
        per_code["file"] = os.path.basename(path)
        detail_rows.append(per_code)

count_df = pd.DataFrame(count_rows)
display(count_df)

if detail_rows:
    detail_df = pd.concat(detail_rows, ignore_index=True)[["file", "組織コード", "row_count"]]
    detail_df = detail_df.sort_values(["file", "組織コード"]).reset_index(drop=True)
    display(detail_df)

       file  matched_rows  matched_unique_codes
0  2022.txt            14                    14
1  2023.txt            14                    14
2  2024.txt            14                    14
3  2025.txt            15                    15
4  2026.txt            14                    14

        file      組織コード  row_count
0   2022.txt  003010100          1
1   2022.txt  003090300          1
2   2022.txt  003090400          1
3   2022.txt  003090500          1
4   2022.txt  003091300          1
..       ...        ...        ...
66  2026.txt  003095410          1
67  2026.txt  003095420          1
68  2026.txt  100A10100          1
69  2026.txt  210A10200          1
70  2026.txt  230H10400          1

[71 rows x 3 columns]

## Remove rows by 組織コード (using existing codes_to_remove and file_paths)

In [75]:
target_codes = {str(c).strip() for c in only_in_actual}

file_paths = [
    r"C:\Users\2372\Downloads\2022.txt",
    r"C:\Users\2372\Downloads\2023.txt",
    r"C:\Users\2372\Downloads\2024.txt",
    r"C:\Users\2372\Downloads\2025.txt",
    r"C:\Users\2372\Downloads\2026.txt",
]

for path in file_paths:
    df_tmp = pd.read_csv(
        path,
        encoding="cp932",
        sep=",",
        on_bad_lines="skip",
        dtype={"組織コード": str},
        keep_default_na=False
    )
    df_tmp.columns = [c.strip() for c in df_tmp.columns]

    if "組織コード" not in df_tmp.columns:
        print(f"{path}: skipped (no '組織コード' column)")
        continue

    before = len(df_tmp)
    df_tmp["組織コード"] = df_tmp["組織コード"].astype(str).str.strip()
    df_tmp = df_tmp[~df_tmp["組織コード"].isin(target_codes)].copy()
    removed = before - len(df_tmp)

    df_tmp.to_csv(path, index=False, encoding="cp932")
    print(f"{path}: removed {removed} rows, remaining {len(df_tmp)}")

C:\Users\2372\Downloads\2022.txt: removed 14 rows, remaining 71
C:\Users\2372\Downloads\2023.txt: removed 14 rows, remaining 73
C:\Users\2372\Downloads\2024.txt: removed 14 rows, remaining 68
C:\Users\2372\Downloads\2025.txt: removed 15 rows, remaining 68
C:\Users\2372\Downloads\2026.txt: removed 14 rows, remaining 71

## Remove row where 合計算入区分 = 0

In [76]:
for path in file_paths:
    df_tmp = pd.read_csv(
        path,
        encoding="cp932",
        sep=",",
        on_bad_lines="skip",
        keep_default_na=False
    )
    df_tmp.columns = [c.strip() for c in df_tmp.columns]

    if "合計算入区分" not in df_tmp.columns:
        print(f"{path}: skipped (no '合計算入区分' column)")
        continue

    before = len(df_tmp)
    kbn = pd.to_numeric(df_tmp["合計算入区分"], errors="coerce")
    df_tmp = df_tmp[kbn != 0].copy()
    removed = before - len(df_tmp)

    df_tmp.to_csv(path, index=False, encoding="cp932")
    print(f"{path}: removed {removed} rows where 合計算入区分=0, remaining {len(df_tmp)}")

C:\Users\2372\Downloads\2022.txt: removed 0 rows where 合計算入区分=0, remaining 71
C:\Users\2372\Downloads\2023.txt: removed 0 rows where 合計算入区分=0, remaining 73
C:\Users\2372\Downloads\2024.txt: removed 0 rows where 合計算入区分=0, remaining 68
C:\Users\2372\Downloads\2025.txt: removed 0 rows where 合計算入区分=0, remaining 68
C:\Users\2372\Downloads\2026.txt: removed 0 rows where 合計算入区分=0, remaining 71

In [50]:
df = pd.read_csv(
        file_paths[0],
        encoding="cp932",
        sep=",",
        on_bad_lines="skip",
        keep_default_na=False
    )
df

,対象年月度,組織コード,組織名,組織名（カナ）,上位組織コード,組織区分,事業所コード,管轄コード,合計算入区分,実績計上区分,出力順,組織ランク,内線電話,責任者名,帳票出力区分,開始日,停止日
0,202303,001000000,イノチオホールディングス㈱,,,5,230H,0,1,0,1,1,,石黒 功,1,2022/02/01,
1,202303,001050100,研究開発本部,,001000000,3,230G,0,1,0,13,2,,梅村 賢司,1,2022/02/01,
2,202303,001060100,管理本部,,001000000,4,230H,0,1,0,2,2,,林 耕一,1,2022/02/01,
3,202303,001090100,イノチオホールディングス本社,,001000000,4,230H,0,1,1,23,2,,,1,2022/02/03,
4,202303,001090200,本社収支,,001000000,4,230H,0,1,1,24,2,,,1,2022/02/03,
5,202303,001091400,中央農業研究所共通,,,4,230G,0,1,1,26,4,,,0,2022/02/03,
6,202303,001091500,高師事業所共通,,,4,230H,0,1,1,25,4,,,0,2022/02/03,
7,202303,001095100,不動産部門,,001000000,4,230H,0,1,1,19,2,,村井 悟,1,2022/02/01,
8,202303,001095200,システム部門,,001000000,4,230H,0,1,1,20,2,,倉員 武志,1,2022/02/02,
9,202303,001095500,事業継承ビジネス,,001000000,4,230H,0,1,1,21,2,,,1,2022/02/03,
10,202303,001095600,花き販売ビジネス,,001000000,4,230H,0,1,1,22,2,,,1,2022/02/03,
11,202303,230G50100,研究開発部,,001050100,3,230G,0,1,0,14,3,,宮地 めぐみ,1,2022/02/01,
12,202303,230G50200,診断分析課,,230G50100,3,230G,0,1,0,15,4,,清水 稔,1,2022/02/01,
13,202303,230G50210,診断分析チーム,,230G50200,3,230G,0,1,1,16,5,,清水 稔,1,2022/02/01,
14,202303,230G50220,技術普及チーム,,230G50200,3,230G,0,1,1,17,5,,岡田 遼太,1,2022/02/01,
15,202303,230G50300,研究開発課,,230G50100,4,230G,0,1,1,18,4,,加藤 泰弘,1,2022/02/01,
16,202303,230H60100,人事総務部,,001060100,4,230H,0,1,0,3,3,,林 耕一,1,2022/02/01,
17,202303,230H60200,総務課,,230H60100,4,230H,0,1,1,4,4,,大谷 弘美,1,2022/02/01,
18,202303,230H60300,人財開発課,,230H60100,4,230H,0,1,1,5,4,,今木 裕介,1,2022/02/01,
19,202303,230H60400,経営管理部,,001060100,4,230H,0,1,0,6,3,,佐藤 政英,1,2022/02/01,
20,202303,230H60500,経理課,,230H60400,4,230H,0,1,1,7,4,,橋本 美穂,1,2022/02/01,
21,202303,230H60600,経営管理課,,230H60400,4,230H,0,1,1,8,4,,村田 智子,1,2022/02/01,
22,202303,230H60700,経営企画部,,001060100,4,230H,0,1,0,9,3,,宮内 徹,1,2022/02/01,
23,202303,230H60800,経営企画課,,230H60700,4,230H,0,1,1,10,4,,宮内 徹,1,2022/02/01,
24,202303,230H60900,デジタルソリューション課,,230H60700,4,230H,0,1,1,11,4,,柴田 恭平,1,2022/02/01,
25,202303,230H61000,統合リスク管理室,,001060100,4,230H,0,1,1,12,3,,小林 英康,1,2022/02/01,

In [53]:
df = df[["組織コード", "組織名"]]

In [ ]:
output_txt_path = os.path.join(r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績", "df_export.txt")
df.to_csv(output_txt_path, index=False, sep=",", encoding="cp932")
print(f"Saved: {output_txt_path}")

Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\df_export.txt

:

## Check difference based on date of a file

In [77]:
import os
import re
import pandas as pd

# =========================
# Input / Output
# =========================
file_paths = [
    r"C:\Users\2372\Downloads\2022.txt",
    r"C:\Users\2372\Downloads\2023.txt",
    r"C:\Users\2372\Downloads\2024.txt",
    r"C:\Users\2372\Downloads\2025.txt",
    r"C:\Users\2372\Downloads\2026.txt",
]

output_dir = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績"
output_path = os.path.join(output_dir, "diff_vs_2025_by_year_ONLY_DIFF_AGRI.txt")


# -------------------------
# Helpers
# -------------------------
def extract_year(path: str) -> str:
    m = re.search(r"(20\d{2})", os.path.basename(path))
    return m.group(1) if m else os.path.basename(path)

def read_year_file(path: str) -> pd.DataFrame:
    df = pd.read_csv(
        path,
        encoding="cp932",
        sep=",",
        on_bad_lines="skip",
        dtype={"組織コード": str},
        keep_default_na=False
    )
    df.columns = [c.strip() for c in df.columns]

    required = {"組織コード", "組織名"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns {missing}. Found: {list(df.columns)}")

    df = df[["組織コード", "組織名"]].copy()
    df["組織コード"] = df["組織コード"].astype(str).str.strip()
    df["組織名"] = df["組織名"].astype(str).str.strip()

    df = df[df["組織コード"] != ""]
    return df.drop_duplicates()

def build_maps(df: pd.DataFrame):
    blank_name_codes = set(df.loc[df["組織名"] == "", "組織コード"].unique().tolist())

    df_nonblank = df[df["組織名"] != ""]
    code_to_name = (
        df_nonblank.groupby("組織コード")["組織名"]
        .agg(lambda s: " / ".join(sorted(set(s))))
        .to_dict()
    )

    name_to_codes = {}
    for c, nm_joined in code_to_name.items():
        for nm in [x.strip() for x in nm_joined.split("/")]:
            if nm:
                name_to_codes.setdefault(nm, set()).add(c)

    return code_to_name, name_to_codes, blank_name_codes


# -------------------------
# Load all years
# -------------------------
year_data = {}
errors = []

for p in file_paths:
    y = extract_year(p)
    try:
        df = read_year_file(p)
        code_to_name, name_to_codes, blank_name_codes = build_maps(df)
        year_data[y] = {
            "code_to_name": code_to_name,
            "name_to_codes": name_to_codes,
            "blank_name_codes": blank_name_codes
        }
    except Exception as e:
        errors.append((p, str(e)))

years_sorted = sorted(year_data.keys())

if "2025" not in year_data:
    raise ValueError("2025 file is required as the reference year.")

ref_2025 = year_data["2025"]["code_to_name"]
ref_2025_names = set(ref_2025.values())
ref_2025_codes = set(ref_2025.keys())


# -------------------------
# Build output
# -------------------------
lines = []
lines.append("=== Compare vs 2025 (BIDIRECTIONAL) ===")
lines.append("A) Codes in 2025 that are changed or missing in another year")
lines.append("B) Codes in another year that do not exist in 2025")
lines.append("C) Names in another year that do not exist in 2025")
lines.append("")

if errors:
    lines.append("=== Read errors ===")
    for p, e in errors:
        lines.append(f"- {p}: {e}")
    lines.append("")

for y in years_sorted:
    if y == "2025":
        continue

    code_to_name = year_data[y]["code_to_name"]
    name_to_codes = year_data[y]["name_to_codes"]
    blank_name_codes = year_data[y]["blank_name_codes"]

    year_codes = set(code_to_name.keys()) | set(blank_name_codes)
    year_names = set(code_to_name.values())

    lines.append(f"==================== {y} vs 2025 ====================")

    # -----------------------------------
    # A) 2025 side: changed / missing
    # -----------------------------------
    lines.append("[A] 2025 codes changed or missing in this year")
    diff_dict = {}

    for code, base_name in ref_2025.items():
        yr_name = code_to_name.get(code, None)

        if yr_name is not None:
            if yr_name != base_name:
                diff_dict[code] = f"2025='{base_name}' | {y}='{yr_name}'"
            continue

        if code in blank_name_codes:
            candidates = sorted(name_to_codes.get(base_name, set()))
            if candidates:
                diff_dict[code] = (
                    f"2025='{base_name}' | {y}='__MISSING_NAME__' "
                    f"(same name found under codes: {', '.join(candidates[:20])}"
                    f"{' ...' if len(candidates) > 20 else ''})"
                )
            else:
                diff_dict[code] = f"2025='{base_name}' | {y}='__MISSING_NAME__'"
            continue

        candidates = sorted(name_to_codes.get(base_name, set()))
        if candidates:
            diff_dict[code] = (
                f"2025='{base_name}' | {y}='__MISSING__' "
                f"(same name found under codes: {', '.join(candidates[:20])}"
                f"{' ...' if len(candidates) > 20 else ''})"
            )
        else:
            diff_dict[code] = f"2025='{base_name}' | {y}='__MISSING__'"

    if diff_dict:
        for code in sorted(diff_dict.keys()):
            lines.append(f"  {code}: {diff_dict[code]}")
    else:
        lines.append("  None")
    lines.append("")

    # -----------------------------------
    # B) Other year side: extra codes
    # -----------------------------------
    lines.append(f"[B] Codes in {y} but not in 2025")
    extra_codes = sorted(year_codes - ref_2025_codes)

    if extra_codes:
        for code in extra_codes:
            if code in code_to_name:
                nm = code_to_name[code]
                lines.append(f"  {code}: {nm}")
            elif code in blank_name_codes:
                lines.append(f"  {code}: __BLANK_NAME__")
    else:
        lines.append("  None")
    lines.append("")

    # -----------------------------------
    # C) Other year side: extra names
    # -----------------------------------
    lines.append(f"[C] Names in {y} but not in 2025")
    extra_names = sorted(year_names - ref_2025_names)

    if extra_names:
        for nm in extra_names:
            codes = sorted(name_to_codes.get(nm, []))
            lines.append(f"  {nm}: codes={', '.join(codes)}")
    else:
        lines.append("  None")
    lines.append("")

# -------------------------
# Save
# -------------------------
os.makedirs(output_dir, exist_ok=True)
with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Saved to: {output_path}")

Saved to: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\diff_vs_2025_by_year_ONLY_DIFF_AGRI.txt

## -----------------------------END-------------------------------------

## Combine all file in a folder

In [11]:
base_folder = r'C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\エノモト'

# # Tìm tất cả các file .txt trong thư mục gốc và các thư mục con
file_list = glob.glob(f"{base_folder}\\*.txt")

# Các cột cần ép kiểu float
float_columns = ['M/P', '予定', '実績', '構成比(%)', '予定比(%)', 'M/P比(%)']

# Đọc và nối tất cả các file
dfs = []
for f in file_list:
    with open(f, 'r', encoding='cp932', errors='ignore') as file:
        if '<!DOCTYPE HTML' in file.read():
            print(f"Bỏ qua file HTML: {f}")
            continue

    df = pd.read_csv(f, encoding="cp932", delimiter='\t', on_bad_lines='skip', dtype={'組織コード': str})
    for col in float_columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col].replace('-', 0), errors='coerce')
    dfs.append(df)

df = pd.concat(dfs, ignore_index=True)
df
# Hiển thị số lượng file đã đọc và số dòng tổng cộng
print(f"Đã đọc {len(file_list)} file.")
print(f"Tổng số dòng: {len(df)}")

# Delete all files in the base_folder
for filename in os.listdir(base_folder):
    file_path = os.path.join(base_folder, filename)
    if os.path.isfile(file_path):
        os.remove(file_path)

print("All files in the folder have been deleted.")

Đã đọc 2 file.
Tổng số dòng: 86
All files in the folder have been deleted.

In [12]:
file_latest = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\エノモト\PKTR022_エノモト_202603.csv"

In [13]:
df.to_csv(file_latest, index=False, sep='\t', encoding="utf-8-sig")

## Check if all dates file has same row numbers

In [ ]:
# file_path_holdings = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\プラントケア\PKTR022_プラントケア_3.csv"

# df_holdings = pd.read_csv(
#     file_path_holdings,
#     delimiter="\t",
#     encoding="utf-8-sig",
#     dtype={"組織コード": str}
# )

# rows_per_org_date = (
#     df_holdings.groupby(["対象年月度", "組織コード"])
#     .size()
#     .reset_index(name="row_count")
# )

# n = 62
# over_n = rows_per_org_date[rows_per_org_date["row_count"] > n] \
#     .sort_values(["対象年月度", "組織コード"]) \
#     .reset_index(drop=True)

# print(f"Total (対象年月度 × 組織コード): {len(rows_per_org_date)}")
# print(f"Combinations with row_count > {n}: {len(over_n)}")

# if over_n.empty:
#     print(f"No date/organization has more than {n} rows.")
# else:
#     display(over_n)

Total (対象年月度 × 組織コード): 50
Combinations with row_count > 62: 0
No date/organization has more than 62 rows.

In [80]:
seikoen_file = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Added Columns\PKTR022_精興園.csv"

df_seikoen = pd.read_csv(
    seikoen_file,
    delimiter="\t",
    encoding="utf-8-sig",
    dtype={"対象年月度": str, "組織コード": str},
    keep_default_na=False
)

result = df_seikoen[
    (df_seikoen["対象年月度"].str.strip() == "202604") &
    (df_seikoen["組織コード"].str.strip() == "004000000")
].copy()

display(result)
print(f"Matched rows: {len(result)}")

Empty DataFrame
Columns: [対象年月度, 組織コード, 明細No., 採算科目名, M/P, 予定, 実績, 構成比(%), 予定比(%), M/P比(%), 組織名, 分類, 採算科目名_経費合計]
Index: []

Matched rows: 0

## Find org code in a folder

In [ ]:
# target_folder = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ"
# target_code = "230B30300"

# txt_files = glob.glob(os.path.join(target_folder, "*.txt"))
# matched_files = []

# for f in txt_files:
#     # Skip HTML-like files
#     with open(f, "r", encoding="cp932", errors="ignore") as fh:
#         if "<!DOCTYPE HTML" in fh.read():
#             continue

#     try:
#         tmp = pd.read_csv(
#             f,
#             encoding="cp932",
#             delimiter="\t",
#             on_bad_lines="skip",
#             dtype={"組織コード": str},
#             usecols=lambda c: c == "組織コード"
#         )
#         if "組織コード" in tmp.columns and tmp["組織コード"].eq(target_code).any():
#             matched_files.append(f)
#     except Exception as e:
#         print(f"Error reading {f}: {e}")

# if matched_files:
#     print(f"Found 組織コード={target_code} in {len(matched_files)} file(s):")
#     for mf in matched_files:
#         print(mf)
# else:
#     print(f"No file contains 組織コード={target_code}.")

Found 組織コード=230B30300 in 3 file(s):
C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\システム設計課_202512.txt
C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\システム設計課_202601.txt
C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\システム設計課_202602.txt

## Count rows in each org code

In [8]:
df_seikoen = pd.read_csv(
    file_latest,
    delimiter="\t",
    encoding="utf-8-sig",
    dtype={"組織コード": str}
)

rows_by_org_date = (
    df_seikoen.groupby(["組織コード", "対象年月度"])
    .size()
    .reset_index(name="row_count")
    .sort_values(["組織コード", "対象年月度"])
    .reset_index(drop=True)
)

display(rows_by_org_date)
print(f"Total (組織コード × 対象年月度): {len(rows_by_org_date)}")

         組織コード   対象年月度  row_count
0    001000000  202204         43
1    001000000  202205         43
2    001000000  202206         43
3    001000000  202207         43
4    001000000  202208         43
..         ...     ...        ...
307  230H61000  202211         43
308  230H61000  202212         43
309  230H61000  202301         43
310  230H61000  202302         43
311  230H61000  202303         43

[312 rows x 3 columns]

Total (組織コード × 対象年月度): 312

## remove row based on company code

In [54]:
df_tmp = pd.read_csv(
    file_latest,
    delimiter="\t",
    encoding="utf-8-sig",
    dtype={"組織コード": str},
    keep_default_na=False
)

df_tmp["組織コード"] = df_tmp["組織コード"].astype(str).str.strip()

before_rows = len(df_tmp)
df_tmp = df_tmp[df_tmp["組織コード"] != "002010200"].copy()
removed_rows = before_rows - len(df_tmp)

df_tmp.to_csv(file_latest, index=False, sep="\t", encoding="utf-8-sig")

print(f"Removed rows (組織コード=002010200): {removed_rows}")
print(f"Remaining rows: {len(df_tmp)}")
print(f"Updated file: {file_latest}")

Removed rows (組織コード=002010200): 124
Remaining rows: 3162
Updated file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\プラントケア\PKTR022_プラントケア_202604.csv

In [29]:
unique_row_counts = rows_by_org_date.groupby("row_count")["組織コード"].unique().reset_index()
unique_row_counts.columns = ["row_count", "組織コード_list"]
unique_row_counts["組織コード_count"] = unique_row_counts["組織コード_list"].apply(len)

for _, r in unique_row_counts.iterrows():
    print(f"row_count = {r['row_count']} ({r['組織コード_count']} unique 組織コード): {sorted(r['組織コード_list'])}")

row_count = 66 (2 unique 組織コード): ['230W10200', '230W60100']

In [27]:
from collections import defaultdict

file_path = r"C:\Users\2372\Downloads\code name postbody.txt"

code_to_names = defaultdict(list)

with open(file_path, "r", encoding="utf-8") as f:
    for line_no, line in enumerate(f, 1):
        line = line.strip()
        if not line:
            continue

        parts = line.split()
        if len(parts) < 3:
            print(f"Skip line {line_no}: not enough columns -> {line}")
            continue

        code = parts[0]
        postbody = parts[-1]          # last column
        name = " ".join(parts[1:-1])  # everything between code and postbody

        code_to_names[code].append(name)

print("Duplicate codes and names:\n")

found = False
for code, names in code_to_names.items():
    if len(names) > 1:
        found = True
        unique_names = list(dict.fromkeys(names))  # remove exact duplicate names, keep order
        print(f"Code: {code}")
        print(f"Count: {len(names)}")
        print("Names:")
        for name in unique_names:
            print(f"  - {name}")
        print("-" * 50)

if not found:
    print("No duplicate code found.")

Duplicate codes and names:

Code: 230G50300
Count: 2
Names:
  - 研究開発課_Date.txt
  - R&Dチーム_Date.txt
--------------------------------------------------
Code: 230H60500
Count: 2
Names:
  - 経理課_Date.txt
  - 財務・経理チーム_Date.txt
--------------------------------------------------

In [13]:
remove_codes = {"230H10100", "230H61500"}

target_file = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\New2.csv"

df_src = pd.read_csv(
    target_file,
    delimiter=",",
    encoding="utf-8-sig",
    dtype={"組織コード": str}
)

df_src["組織コード"] = df_src["組織コード"].astype(str).str.strip()

before_rows = len(df_src)
df_clean = df_src[~df_src["組織コード"].isin(remove_codes)].copy()
removed_rows = before_rows - len(df_clean)

df_clean.to_csv(target_file, index=False, sep="\t", encoding="utf-8-sig")

print(f"Removed rows: {removed_rows}")
print(f"Remaining rows: {len(df_clean)}")
print(f"Updated file: {target_file}")

Removed rows: 8804
Remaining rows: 13818
Updated file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\New2.csv

In [34]:
import os
import re
import glob
import pandas as pd

base_folder = r'C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園'
file_list = glob.glob(os.path.join(base_folder, "*.txt"))

target_names = [ "イノチオ精興園㈱",
  "イノチオ精興園本社",
  "本社収支",
  "一般ユーザー権限",
  "経営管理者権限",
  "システム管理者権限",
  "鵜飼事業所共通",
  "田原試験農場共通",
  "芦田事業所共通",
  "バラ課",
  "営業部",
  "営業課",
  "営業チーム",
  "セットチーム",
  "苗販売課",
  "知財管理チーム",
  "管理部",
  "管理課",
  "種苗部",
  "苗品質管理課",
  "繁殖チーム",
  "通販課",
  "育種開発部",
  "ブリーディングチーム",
  "海外事業課",
  "育種開発課",
  "交配チーム",
  "金丸開発生産課",
  "栽培管理チーム" ]

for fp in file_list:
    try:
        # skip html/error files
        with open(fp, "r", encoding="cp932", errors="ignore") as fh:
            content = fh.read()
            if "<!DOCTYPE HTML" in content:
                print(f"Skip HTML file: {fp}")
                continue

        # get file name without extension
        base_name = os.path.splitext(os.path.basename(fp))[0]

        # remove trailing _YYYYMM
        company_name = re.sub(r"_\d{6}$", "", base_name).strip()

        # process only target company names
        if company_name not in target_names:
            print(f"Skip non-target file: {base_name}")
            continue

        # read txt
        df = pd.read_csv(
            fp,
            encoding="cp932",
            delimiter="\t",
            on_bad_lines="skip"
        )

        # clean column names
        df.columns = [c.strip() for c in df.columns]

        # add 組織名 column
        df["組織名"] = company_name

        # save back to same file
        df.to_csv(fp, sep="\t", index=False, encoding="cp932")

        print(f"Saved: {fp} -> 組織名 = {company_name}")

    except Exception as e:
        print(f"Skip {fp}: {e}")

Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\イノチオ精興園㈱_202604.txt -> 組織名 = イノチオ精興園㈱
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\イノチオ精興園本社_202604.txt -> 組織名 = イノチオ精興園本社
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\システム管理者権限_202604.txt -> 組織名 = システム管理者権限
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\セットチーム_202604.txt -> 組織名 = セットチーム
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\バラ課_202604.txt -> 組織名 = バラ課
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\ブリーディングチーム_202604.txt -> 組織名 = ブリーディングチーム
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\一般ユーザー権限_202604.txt -> 組織名 = 一般ユーザー権限
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\交配チーム_202604.txt -> 組織名 = 交配チーム
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\営業チーム_202604.txt -> 組織名 = 営業チーム
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\営業課_202604.txt -> 組織名 = 営業課
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\営業部_202604.txt -> 組織名 = 営業部
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\本社収支_202604.txt -> 組織名 = 本社収支
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\栽培管理チーム_202604.txt -> 組織名 = 栽培管理チーム
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\海外事業課_202604.txt -> 組織名 = 海外事業課
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\田原試験農場共通_202604.txt -> 組織名 = 田原試験農場共通
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\知財管理チーム_202604.txt -> 組織名 = 知財管理チーム
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\種苗部_202604.txt -> 組織名 = 種苗部
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\管理課_202604.txt -> 組織名 = 管理課
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\管理部_202604.txt -> 組織名 = 管理部
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\経営管理者権限_202604.txt -> 組織名 = 経営管理者権限
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\繁殖チーム_202604.txt -> 組織名 = 繁殖チーム
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\育種開発課_202604.txt -> 組織名 = 育種開発課
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\育種開発部_202604.txt -> 組織名 = 育種開発部
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\芦田事業所共通_202604.txt -> 組織名 = 芦田事業所共通
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\苗品質管理課_202604.txt -> 組織名 = 苗品質管理課
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\苗販売課_202604.txt -> 組織名 = 苗販売課
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\通販課_202604.txt -> 組織名 = 通販課
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\金丸開発生産課_202604.txt -> 組織名 = 金丸開発生産課
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\鵜飼事業所共通_202604.txt -> 組織名 = 鵜飼事業所共通

In [18]:
target_folder = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ"
output_path = os.path.join(target_folder, "New3.txt")

file_list = [
    fp for fp in glob.glob(os.path.join(target_folder, "*.txt"))
    if os.path.abspath(fp) != os.path.abspath(output_path)
]

dfs = []
for fp in file_list:
    try:
        with open(fp, "r", encoding="cp932", errors="ignore") as fh:
            if "<!DOCTYPE HTML" in fh.read():
                print(f"Skip HTML file: {fp}")
                continue

        df_tmp = pd.read_csv(
            fp,
            encoding="cp932",
            delimiter="\t",
            on_bad_lines="skip",
            dtype={"組織コード": str},
            keep_default_na=False
        )
        df_tmp.columns = [c.strip() for c in df_tmp.columns]
        dfs.append(df_tmp)

    except Exception as e:
        print(f"Skip {fp}: {e}")

combined_df = pd.concat(dfs, ignore_index=True)
combined_df.to_csv(output_path, index=False, sep="\t", encoding="utf-8-sig")

deleted_count = 0
for fp in file_list:
    try:
        os.remove(fp)
        deleted_count += 1
    except Exception as e:
        print(f"Could not delete {fp}: {e}")

print(f"Saved: {output_path}")
print(f"Combined rows: {len(combined_df)}")
print(f"Deleted txt files: {deleted_count}")

Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202304.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202305.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202306.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202307.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202308.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202309.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202310.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202311.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202312.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202401.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202402.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202403.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202404.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202405.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202406.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202407.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202408.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202409.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202410.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202411.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202412.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202501.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202502.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\営業本部室_202503.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202304.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202305.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202306.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202307.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202308.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202309.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202310.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202311.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202312.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202401.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202402.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202403.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202404.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202405.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202406.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202407.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202408.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202409.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202410.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202411.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202412.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202501.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202502.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\推進チーム_202503.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202404.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202405.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202406.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202407.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202408.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202409.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202410.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202411.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202412.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202501.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202502.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\海外資材課_202503.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202404.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202405.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202406.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202407.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202408.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202409.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202410.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202411.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202412.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202501.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202502.txt
Skip HTML file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\購買課_202503.txt
Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\New3.txt
Combined rows: 8804
Deleted txt files: 196

In [19]:
new_txt_path = output_path
new_csv_path = os.path.splitext(new_txt_path)[0] + ".csv"

df_new1 = pd.read_csv(
    new_txt_path,
    delimiter="\t",
    encoding="utf-8-sig",
    dtype={"組織コード": str}
)

df_new1.to_csv(new_csv_path, index=False, encoding="utf-8-sig")
print(f"Saved: {new_csv_path}")

Saved: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\New3.csv

In [20]:
import os
import pandas as pd

# Paths
new1_path = os.path.join(target_folder, "New1.csv")
new2_path = os.path.join(target_folder, "New2.csv")
new3_path = os.path.join(target_folder, "New3.csv")
update_path = os.path.join(target_folder, "PKTR022_アグリ_Update.csv")

# Files to append
new_files = [
    ("New1.csv", new1_path, ","),
    ("New2.csv", new2_path, "\t"),
    ("New3.csv", new3_path, ","),
]

dfs_to_concat = []

# 1) Load existing _Update.csv first if it exists
if os.path.exists(update_path):
    df_update = pd.read_csv(
        update_path,
        delimiter="\t",
        encoding="utf-8-sig",
        dtype={"組織コード": str},
        keep_default_na=False,
        on_bad_lines="skip"
    )
    df_update.columns = [c.strip() for c in df_update.columns]
    dfs_to_concat.append(df_update)
    print(f"Loaded existing update file: {len(df_update)} rows")
else:
    print("No existing _Update.csv found. A new one will be created.")

# 2) Load New1 / New2 / New3
loaded_new_files = []

for label, path, sep in new_files:
    if not os.path.exists(path):
        print(f"Skip (not found): {label} -> {path}")
        continue

    df_part = pd.read_csv(
        path,
        delimiter=sep,
        encoding="utf-8-sig",
        dtype={"組織コード": str},
        keep_default_na=False,
        on_bad_lines="skip"
    )
    df_part.columns = [c.strip() for c in df_part.columns]
    dfs_to_concat.append(df_part)
    loaded_new_files.append(path)
    print(f"Loaded {label}: {len(df_part)} rows")

# 3) Save merged result
if not dfs_to_concat:
    print("No files loaded. Nothing to save.")
else:
    merged_df = pd.concat(dfs_to_concat, ignore_index=True)
    merged_df.to_csv(update_path, index=False, sep="\t", encoding="utf-8-sig")

    print(f"Saved merged file: {update_path}")
    print(f"Total rows: {len(merged_df)}")

    # 4) Delete New1 / New2 / New3 after successful save
    for path in loaded_new_files:
        try:
            os.remove(path)
            print(f"Deleted: {path}")
        except Exception as e:
            print(f"Could not delete {path}: {e}")

Loaded existing update file: 100217 rows
Loaded New1.csv: 20727 rows
Loaded New2.csv: 13818 rows
Loaded New3.csv: 8804 rows
Saved merged file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\PKTR022_アグリ_Update.csv
Total rows: 143566
Deleted: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\New1.csv
Deleted: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\New2.csv
Deleted: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\New3.csv

## For Agri

### Print files in a group of row count

In [31]:
# Print groups by row count using 組織コード (not file/org name)
org_code_df = pd.DataFrame(
    [
        {
            "rows": len(d),
            "組織コード": str(d["組織コード"].dropna().iloc[0]) if ("組織コード" in d.columns and not d["組織コード"].dropna().empty) else None
        }
        for d in dfs
        if isinstance(d, pd.DataFrame) and not d.empty
    ] 
).dropna(subset=["組織コード"])

grouped_codes = (
    org_code_df.groupby("rows")["組織コード"]
    .apply(lambda s: sorted(set(s)))
    .reset_index(name="org_codes")
    .sort_values("rows")
    .reset_index(drop=True)
)

for _, r in grouped_codes.iterrows():
    print(f"Rows = {int(r['rows'])} ({len(r['org_codes'])} unique 組織コード)")
    for code in r["org_codes"]:
        print(f"  - {code}")
    print()

Rows = 70 (30 unique 組織コード)
  - 003030100
  - 003095320
  - 003095420
  - 040A30101
  - 040A30201
  - 100A30101
  - 220C30101
  - 230A30101
  - 230B10100
  - 230B30100
  - 230B30200
  - 230B30300
  - 230B30601
  - 230B50100
  - 230C30200
  - 230C30310
  - 230C30330
  - 230C30400
  - 230C30500
  - 230C30600
  - 230H30200
  - 230J30100
  - 230K10300
  - 230K30101
  - 230P10100
  - 230P30101
  - 230Q30101
  - 230S30101
  - 400A10100
  - 400A30100

Rows = 71 (33 unique 組織コード)
  - 003060100
  - 003090100
  - 003090200
  - 003090300
  - 003090400
  - 003090500
  - 003091300
  - 003091500
  - 003092100
  - 003095310
  - 003095410
  - 040A10100
  - 040A10200
  - 100A10200
  - 220C10100
  - 230A10200
  - 230B10200
  - 230B60100
  - 230C60100
  - 230H10100
  - 230H10200
  - 230H10500
  - 230H61100
  - 230H61210
  - 230H61500
  - 230H61600
  - 230H61800
  - 230H62000
  - 230K10100
  - 230P10300
  - 230Q10200
  - 230S10200
  - 400A10200

Rows = 87 (17 unique 組織コード)
  - 003000000
  - 003010100
  - 040A10300
  - 040A10400
  - 100A10100
  - 100A10300
  - 220C10200
  - 230A10100
  - 230A10300
  - 230B10300
  - 230H10400
  - 230H10600
  - 230K10200
  - 230P10400
  - 230Q10300
  - 230S10300
  - 400A10300

### Check if essential 組織コード is enough or lack

In [33]:
# Check row count consistency by (対象年月度, 組織コード)
check_file = r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\PKTR022_アグリ_2025.csv"

df_check = pd.read_csv(
    check_file,
    delimiter="\t",
    encoding="utf-8-sig",
    dtype={"組織コード": str}
)

codes_70 = [
"003030100", "003095320", "003095420", "040A30101", "040A30201",
"100A30101", "220C30101", "230A30101", "230B10100", "230B30100",
"230B30200", "230B30300", "230B30601", "230B50100", "230C30200",
"230C30310", "230C30330", "230C30400", "230C30500", "230C30600",
"230H30200", "230J30100", "230K10300", "230K30101", "230P10100",
"230P30101", "230Q30101", "230S30101", "400A10100", "400A30100"
]

codes_71 = [
"003060100", "003090100", "003090200", "003090300", "003090400",
"003090500", "003091300", "003091500", "003092100", "003095310",
"003095410", "040A10100", "040A10200", "100A10200", "220C10100",
"230A10200", "230B10200", "230B60100", "230C60100", "230H10100",
"230H10200", "230H10500", "230H61100", "230H61210", "230H61500",
"230H61600", "230H61800", "230H62000", "230K10100", "230P10300",
"230Q10200", "230S10200", "400A10200"
]

codes_87 = [
"003000000", "003010100", "040A10300", "040A10400", "100A10100",
"100A10300", "220C10200", "230A10100", "230A10300", "230B10300",
"230H10400", "230H10600", "230K10200", "230P10400", "230Q10300",
"230S10300", "400A10300"
]

expected_rows = {c: 70 for c in codes_70}
expected_rows.update({c: 71 for c in codes_71})
expected_rows.update({c: 87 for c in codes_87})

actual = (
    df_check.groupby(["対象年月度", "組織コード"])
    .size()
    .reset_index(name="actual_rows")
)
actual["expected_rows"] = actual["組織コード"].map(expected_rows)

mismatch = actual[
    actual["expected_rows"].isna() | (actual["actual_rows"] != actual["expected_rows"])
].sort_values(["組織コード", "対象年月度"]).reset_index(drop=True)

print(f"Checked records: {len(actual)} (年月度 × 組織コード)")
print(f"Mismatches found: {len(mismatch)}")

if mismatch.empty:
    print("All 組織コード row counts match expected (67/71/84).")
else:
    print("Mismatch details:")
    display(mismatch)

    unknown_codes = sorted(mismatch.loc[mismatch["expected_rows"].isna(), "組織コード"].unique().tolist())
    if unknown_codes:
        print(f"Codes not in expected lists ({len(unknown_codes)}): {unknown_codes}")

Checked records: 960 (年月度 × 組織コード)
Mismatches found: 0
All 組織コード row counts match expected (67/71/84).

### Show mismatch details at unique 組織コード level only (ignore 対象年月度)

In [23]:
if mismatch.empty:
    print("No mismatches.")
else:
    mismatch_unique_codes = sorted(mismatch["組織コード"].dropna().astype(str).unique().tolist())
    print(f"Unique mismatched 組織コード: {len(mismatch_unique_codes)}")
    display(pd.DataFrame({"組織コード": mismatch_unique_codes}))

No mismatches.

### Remove unecessary 組織コード

In [8]:
# Remove specific 組織コード rows from the target file, then overwrite the same file
remove_codes = {"003010100", "100A10100", "230A10100", "230H10400"}

df_src = pd.read_csv(
    check_file,  # already set to: ...\アグリ_202204_202511.csv
    delimiter="\t",
    encoding="utf-8-sig",
    dtype={"組織コード": str}
)

before_rows = len(df_src)
df_clean = df_src[~df_src["組織コード"].isin(remove_codes)].copy()
removed_rows = before_rows - len(df_clean)

df_clean.to_csv(check_file, index=False, sep="\t", encoding="utf-8-sig")

print(f"Removed rows: {removed_rows}")
print(f"Remaining rows: {len(df_clean)}")
print(f"Updated file: {check_file}")

Removed rows: 252
Remaining rows: 4735
Updated file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\アグリ\PKTR022_アグリ_４.csv

## Total unique files (ignoring trailing _YYYYMM in file names)

In [14]:
tmp_unique = pd.DataFrame({"file_path": file_list})
tmp_unique["base_name"] = tmp_unique["file_path"].map(lambda p: os.path.splitext(os.path.basename(p))[0])

# Ignore trailing _YYYYMM in file names
tmp_unique["base_name"] = tmp_unique["base_name"].map(
	lambda s: s.rsplit("_", 1)[0]
	if len(s.rsplit("_", 1)) == 2 and s.rsplit("_", 1)[1].isdigit() and len(s.rsplit("_", 1)[1]) == 6
	else s
)

total_unique_files = tmp_unique["base_name"].nunique()
print(f"Total unique files: {total_unique_files}")

Total unique files: 17

# Add Columns

### Check if 組織コード of a file match with expected 組織コード

In [23]:
# Read the CSV file
file_latest = r'C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\プラントケア\PKTR022_プラントケア_４.csv'
df_check = pd.read_csv(file_latest, delimiter='\t', encoding="utf-8-sig")

# Define the expected list
expected_codes = [
       '002000000', '002090100', '230I10300', '230I10100', '300A10100',
       '230I10200', '002010200', '060C10100', '230R10100', '230S10100',
       '060A10200', '270A10100', '220B10200', '060E10100', '060D10100',
       '002090200', '230I10500', '230I10400', '230I60300', '230I60210',
       '230I60500', '060A10100', '060B60100', '060A60100', '060A60200',
       '060B10100', '230I11000', '230I60200', '002010300', '230I10800',
       '230I10600', '300B10100', '220D10300', '070A10100', '002060100',
       '230I60100', '220D60400', '220D30200', '220D30100', '230I10900',
       '230I10700', '230I60400', '220A10100'
    ]

# Get unique codes from the CSV
actual_codes = df_check['組織コード'].unique().tolist()

# Check if they match exactly
is_exact_match = set(actual_codes) == set(expected_codes)
print(f"Exact match: {is_exact_match}")

# Show differences if any
missing_codes = set(expected_codes) - set(actual_codes)
extra_codes = set(actual_codes) - set(expected_codes)

if missing_codes:
    print(f"Missing codes: {missing_codes}")
if extra_codes:
    print(f"Extra/Redundant codes: {extra_codes}")

Exact match: False
Missing codes: {'230I60200', '060A60100', '230I10100', '220D30100'}

## Remove unecessary 組織コード if it's exra/redundant

In [18]:
# Remove specific 組織コード rows from the target file, then overwrite the same file
remove_codes = {'002091200', '002091600', '002091100', '002090400', '002090300', '002092200', '002090500'} # extra_codes

df_src = pd.read_csv(
    file_latest, 
    delimiter="\t",
    encoding="utf-8-sig",
    dtype={"組織コード": str}
)

before_rows = len(df_src)
df_clean = df_src[~df_src["組織コード"].isin(remove_codes)].copy()
removed_rows = before_rows - len(df_clean)

df_clean.to_csv(file_latest, index=False, sep="\t", encoding="utf-8-sig")

print(f"Removed rows: {removed_rows}")
print(f"Remaining rows: {len(df_clean)}")
print(f"Updated file: {file_latest}")

Removed rows: 434
Remaining rows: 2418
Updated file: C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\プラントケア\PKTR022_プラントケア_４.csv

In [62]:
df = pd.read_csv(r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\精興園\PKTR022_精興園_202604.csv", delimiter='\t', encoding="utf-8-sig")
df

,対象年月度,組織コード,明細No.,採算科目名,M/P,予定,実績,構成比(%),予定比(%),M/P比(%)
0,202604,4000000,1,総受注高,173001400.0,171968560.0,71040210.0,NaN,41.3,41.0
1,202604,4000000,2,許諾料,2000000.0,2000000.0,1570000.0,2.2,78.5,78.5
2,202604,4000000,3,穂木,116220000.0,116220000.0,22272950.0,31.3,19.1,19.1
3,202604,4000000,4,ﾛｲﾔﾙﾃｨ,36705000.0,36705000.0,35869919.0,50.4,97.7,97.7
4,202604,4000000,5,バラ,6912000.0,5910000.0,5403227.0,7.6,91.4,78.1
...,...,...,...,...,...,...,...,...,...,...
769,202604,4091800,82,移動時間,0.0,0.0,0.0,NaN,0.0,0.0
770,202604,4091800,83,部門共通（時間）,0.0,0.0,0.0,NaN,0.0,0.0
771,202604,4091800,84,全社共通（時間）,0.0,0.0,0.0,NaN,0.0,0.0
772,202604,4091800,85,当月時間当り,0.0,0.0,0.0,NaN,0.0,0.0
773,202604,4091800,86,人員,0.0,0.0,0.0,NaN,0.0,0.0

In [14]:
import pandas as pd

# Load the CSV file into df_flo with proper delimiter
df = pd.read_csv(r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Latest Date\エノモト\PKTR022_エノモト_202603.csv", 
                 delimiter='\t', encoding="utf-8-sig", dtype={'組織コード': str})

#Filter 組織コード

target_org_codes = ['210A10200', '017000000']


df = df[df['組織コード'].isin(target_org_codes)]

# Add 組織名 column using mapping

mapping = {
  "210A10200": "エノモト農材",
  "017000000": "㈱エノモト農材"
}


df['組織名'] = df['組織コード'].map(mapping).fillna('不明な組織')

 # Add 分類 column
def get_category(row):
     if row['明細No.'] == 1:
         return "受注"
     elif 3 <= row['明細No.'] <= 6:
         return "売上"
     elif 13 <= row['明細No.'] <= 35:
         return "経費"
     elif 39 <= row['明細No.'] <= 41:
         return "時間"
     else:
         return None


    # For Agri 
    # n = expected_rows.get(row['組織コード'])
    # d = row['明細No.']

    # if n == 70:
    #     if 9 <= row['明細No.'] <= 61 and row['明細No.'] != 15:
    #      return "経費"
    #     elif 65 <= row['明細No.'] <= 68:
    #         return "時間"
    #     else:
    #         return None

    # elif n == 71:
    #     if 2 <= d <= 4:
    #         return "受注"
    #     elif 6 <= d <= 11:
    #         return "売上"
    #     elif 19 <= d <= 62:
    #         return "経費"
    #     elif 66 <= d <= 69:
    #         return "時間"
    #     else:
    #         return None

    # elif n == 87:
    #     if 2 <= row['明細No.'] <= 4:
    #      return "受注"
    #     elif 6 <= row['明細No.'] <= 11:
    #      return "売上"
    #     elif 26 <= row['明細No.'] <= 78 and row['明細No.'] != 32:
    #      return "経費"
    #     elif 82 <= row['明細No.'] <= 85:
    #      return "時間"
    #     else:
    #      return None

    # return None

df['分類'] = df.apply(get_category, axis=1)

# Add 採算科目名_経費合計 based on calculated 分類
df['採算科目名_経費合計'] = df['採算科目名'].where(df['分類'] == '経費')

## Concat files

In [15]:
import pandas as pd

file_name = r'C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Added Columns\PKTR022_エノモト.csv'

original_df = pd.read_csv(file_name, delimiter='\t', encoding="utf-8-sig")

combined_df = pd.concat([df, original_df], ignore_index=True)
combined_df.to_csv(file_name, index=False, sep='\t', encoding="utf-8-sig")

In [16]:
# Filter the file for specific 組織コード and 対象年月度
result = pd.read_csv(
    r"C:\Users\2372\OneDrive - イノチオホールディングス株式会社\採算表_RPA\実績\Added Columns\PKTR022_アグリコ.csv",
    delimiter='\t',
    encoding='utf-8-sig',
    dtype={'組織コード': str, '対象年月度': str}
)

result = result[
    (result['組織コード'].str.strip() == '013000000') &
    (result['対象年月度'].astype(str).str.strip() == '202604')
].copy()

display(result)
print(f"Matched rows: {len(result)}")

,対象年月度,組織コード,明細No.,採算科目名,M/P,予定,実績,構成比(%),予定比(%),M/P比(%),組織名,分類,採算科目名_経費合計
44,202604,013000000,1,総受注高,37080000.0,38780000.0,46450126.0,NaN,119.7,125.2,㈱アグリコ,受注,NaN
45,202604,013000000,2,総売上高,37080000.0,38780000.0,46450126.0,NaN,119.7,125.2,㈱アグリコ,NaN,NaN
46,202604,013000000,3,売上高,37980000.0,39680000.0,46972952.0,NaN,118.3,123.6,㈱アグリコ,売上,NaN
47,202604,013000000,4,売上値引,-900000.0,-900000.0,-522826.0,NaN,0.0,0.0,㈱アグリコ,売上,NaN
48,202604,013000000,5,売上原価,29450000.0,30880000.0,38741473.0,NaN,125.4,131.5,㈱アグリコ,NaN,NaN
49,202604,013000000,6,総収益,7630000.0,7900000.0,7708653.0,16.5,97.5,101.0,㈱アグリコ,NaN,NaN
50,202604,013000000,7,経費合計,3738021.0,3712494.0,3855886.0,8.3,103.8,103.1,㈱アグリコ,NaN,NaN
51,202604,013000000,8,減価償却費,161156.0,161156.0,159434.0,0.3,98.9,98.9,㈱アグリコ,経費,減価償却費
52,202604,013000000,9,車両費,175720.0,175720.0,150145.0,0.3,85.4,85.4,㈱アグリコ,経費,車両費
53,202604,013000000,10,旅費交通費,50000.0,50000.0,13819.0,0.0,27.6,27.6,㈱アグリコ,経費,旅費交通費
54,202604,013000000,11,荷造運搬費,181000.0,181000.0,181320.0,0.3,100.1,100.1,㈱アグリコ,経費,荷造運搬費
55,202604,013000000,12,通信費,48170.0,48170.0,45068.0,0.0,93.5,93.5,㈱アグリコ,経費,通信費
56,202604,013000000,13,水道光熱費,92000.0,92000.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,水道光熱費
57,202604,013000000,14,事務用品費,33250.0,33250.0,301945.0,0.6,908.1,908.1,㈱アグリコ,経費,事務用品費
58,202604,013000000,15,消耗品費,59700.0,59700.0,2000.0,0.0,3.3,3.3,㈱アグリコ,経費,消耗品費
59,202604,013000000,16,広告宣伝費,800.0,800.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,広告宣伝費
60,202604,013000000,17,接待交際費,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,接待交際費
61,202604,013000000,18,賃借料,371500.0,371500.0,385819.0,0.8,103.8,103.8,㈱アグリコ,経費,賃借料
62,202604,013000000,19,修繕費,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,修繕費
63,202604,013000000,20,支払リース料,9100.0,9100.0,9100.0,0.0,100.0,100.0,㈱アグリコ,経費,支払リース料
64,202604,013000000,21,保険料,84980.0,84980.0,84980.0,0.1,100.0,100.0,㈱アグリコ,経費,保険料
65,202604,013000000,22,支払手数料,145600.0,145600.0,229621.0,0.4,157.7,157.7,㈱アグリコ,経費,支払手数料
66,202604,013000000,23,諸会費,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,諸会費
67,202604,013000000,24,会議費,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,会議費
68,202604,013000000,25,寄付金,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,寄付金
69,202604,013000000,26,租税公課,2000.0,2000.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,租税公課
70,202604,013000000,27,貸倒金,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,貸倒金
71,202604,013000000,28,情報機器利用料,150800.0,150800.0,155730.0,0.3,103.2,103.2,㈱アグリコ,経費,情報機器利用料
72,202604,013000000,29,雑費,29527.0,4000.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,雑費
73,202604,013000000,30,新聞図書費,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,新聞図書費
74,202604,013000000,32,雑給,6000.0,6000.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,雑給
75,202604,013000000,33,社内金利（固定資産）,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,社内金利（固定資産）
76,202604,013000000,34,社内金利（売掛金）,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,社内金利（売掛金）
77,202604,013000000,35,部門共通（経費）,0.0,0.0,0.0,0.0,0.0,0.0,㈱アグリコ,経費,部門共通（経費）
78,202604,013000000,36,グループ共通,2136000.0,2136000.0,86000.0,0.1,4.0,4.0,㈱アグリコ,経費,グループ共通
79,202604,013000000,37,差引収益,3891979.0,4187506.0,3852767.0,8.2,92.0,98.9,㈱アグリコ,NaN,NaN
80,202604,013000000,38,差引比率,10.4,10.7,8.2,NaN,76.6,78.8,㈱アグリコ,NaN,NaN
81,202604,013000000,39,総時間,1331.0,1331.0,1381.5,NaN,103.7,103.7,㈱アグリコ,NaN,NaN
82,202604,013000000,40,定時間,1230.0,1230.0,1196.5,NaN,97.2,97.2,㈱アグリコ,時間,NaN
83,202604,013000000,41,残業時間,101.0,101.0,185.0,NaN,183.1,183.1,㈱アグリコ,時間,NaN
84,202604,013000000,42,移動時間,0.0,0.0,0.0,NaN,0.0,0.0,㈱アグリコ,時間,NaN
85,202604,013000000,43,部門共通（時間）,0.0,0.0,0.0,NaN,0.0,0.0,㈱アグリコ,時間,NaN
86,202604,013000000,44,当月時間当り,2924.1,3146.1,2788.8,NaN,88.6,95.3,㈱アグリコ,NaN,NaN
87,202604,013000000,45,人員,7.0,7.0,7.0,NaN,100.0,100.0,㈱アグリコ,NaN,NaN

Matched rows: 44

## Check row numbers based on date of each 組織コード

In [34]:
# Load the file and check 対象年月度 consistency per 組織コード
df_new = pd.read_csv(
    file_name,
    delimiter='\t',
    encoding='utf-8-sig',
    dtype={'組織コード': str}
)

# Group by 組織コード and 対象年月度, count rows
consistency_check = (
    df_new.groupby(['組織コード', '対象年月度'])
    .size()
    .reset_index(name='row_count')
)

# Find mismatches (rows != 84)
mismatches = consistency_check[consistency_check['row_count'] != 84].sort_values(['組織コード', '対象年月度']).reset_index(drop=True)

print(f"Total (組織コード × 対象年月度) combinations: {len(consistency_check)}")
print(f"Mismatches found (row_count ≠ 84): {len(mismatches)}")
print()

if mismatches.empty:
    print("✓ All combinations have exactly 84 rows.")
else:
    print("Mismatch details:")
    display(mismatches)

Total (組織コード × 対象年月度) combinations: 172
Mismatches found (row_count ≠ 84): 172

Mismatch details:

         組織コード   対象年月度  row_count
0    014000000  202204         66
1    014000000  202205         66
2    014000000  202206         66
3    014000000  202207         66
4    014000000  202208         66
..         ...     ...        ...
167  230W60100  202311         66
168  230W60100  202312         66
169  230W60100  202401         66
170  230W60100  202402         66
171  230W60100  202403         66

[172 rows x 3 columns]

# Create 分類 table

In [ ]:
# import pandas as pd

# # Create the table as a DataFrame
# table_data = {
#     "分類": ["受注", "売上", "収益", "経費", "時間"],
#     "分類順": [1, 2, 3, 4, 5]
# }
# table_df = pd.DataFrame(table_data)

# # Save to CSV
# table_df.to_csv("Added Columns/分類Table.csv", index=False, sep='\t', encoding="utf-8-sig")